pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - status-success=Build and Test (ubuntu-latest, 2.13.5, adopt@1.8)
      - body~=labels:.*semver-patch
    actions:
      merge:
        method: merge
