(function(){
'use strict';var e,aa=Object.freeze({esVersion:6,assumingES6:!0,productionMode:!0,linkerVersion:"1.12.0",fileLevelThis:this}),ba;function ca(a){for(var b in a)return b}function k(a){this.Ra=a}k.prototype.toString=function(){return String.fromCharCode(this.Ra)};var ea=function da(a,b,c){var f=new a.ha(b[c]);if(c<b.length-1){a=a.O;c+=1;for(var h=f.c,g=0;g<h.length;g++)h[g]=da(a,b,c)}return f};
function fa(a){switch(typeof a){case "string":return l(ha);case "number":return ia(a)?a<<24>>24===a?l(ja):a<<16>>16===a?l(ka):l(la):ma(a)?l(na):l(oa);case "boolean":return l(pa);case "undefined":return l(qa);default:return null===a?a.Bb():a instanceof n?l(ra):a instanceof k?l(sa):a&&a.$classData?l(a.$classData):null}}
function ta(a){switch(typeof a){case "string":return"java.lang.String";case "number":return ia(a)?a<<24>>24===a?"java.lang.Byte":a<<16>>16===a?"java.lang.Short":"java.lang.Integer":ma(a)?"java.lang.Float":"java.lang.Double";case "boolean":return"java.lang.Boolean";case "undefined":return"java.lang.Void";default:return null===a?a.Bb():a instanceof n?"java.lang.Long":a instanceof k?"java.lang.Character":a&&a.$classData?a.$classData.name:null.D.name}}
function ua(a){switch(typeof a){case "string":return q(a);case "number":return va(a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||null===a?a.u():a instanceof n?a.K^a.J:a instanceof k?null===a?0:a.Ra:r.prototype.u.call(a)}}var wa=0,xa=new WeakMap;
function ya(a){switch(typeof a){case "string":return q(a);case "number":return va(a);case "bigint":var b=0;for(a<BigInt(0)&&(a=~a);a!==BigInt(0);)b^=Number(BigInt.asIntN(32,a)),a>>=BigInt(32);return b;case "boolean":return a?1231:1237;case "undefined":return 0;case "symbol":return a=a.description,void 0===a?0:q(a);default:if(null===a)return 0;b=xa.get(a);void 0===b&&(wa=b=wa+1|0,xa.set(a,b));return b}}function ia(a){return"number"===typeof a&&(a|0)===a&&1/a!==1/-0}
function ma(a){return"number"===typeof a&&(a!==a||Math.fround(a)===a)}function r(){}r.prototype.constructor=r;function t(){}t.prototype=r.prototype;r.prototype.u=function(){return ya(this)};r.prototype.i=function(){var a=this.u();return ta(this)+"@"+(+(a>>>0)).toString(16)};r.prototype.toString=function(){return this.i()};function u(a){if("number"===typeof a){this.c=Array(a);for(var b=0;b<a;b++)this.c[b]=null}else this.c=a}u.prototype=new t;u.prototype.constructor=u;function za(){}za.prototype=u.prototype;
function Aa(a){if("number"===typeof a){this.c=Array(a);for(var b=0;b<a;b++)this.c[b]=!1}else this.c=a}Aa.prototype=new t;Aa.prototype.constructor=Aa;function Ba(a){this.c="number"===typeof a?new Uint16Array(a):a}Ba.prototype=new t;Ba.prototype.constructor=Ba;function Ca(a){this.c="number"===typeof a?new Int8Array(a):a}Ca.prototype=new t;Ca.prototype.constructor=Ca;function Da(a){this.c="number"===typeof a?new Int16Array(a):a}Da.prototype=new t;Da.prototype.constructor=Da;
function Ea(a){this.c="number"===typeof a?new Int32Array(a):a}Ea.prototype=new t;Ea.prototype.constructor=Ea;function Fa(a){if("number"===typeof a){this.c=Array(a);for(var b=0;b<a;b++)this.c[b]=ba}else this.c=a}Fa.prototype=new t;Fa.prototype.constructor=Fa;function Ga(a){this.c="number"===typeof a?new Float32Array(a):a}Ga.prototype=new t;Ga.prototype.constructor=Ga;function Ha(a){this.c="number"===typeof a?new Float64Array(a):a}Ha.prototype=new t;Ha.prototype.constructor=Ha;
function v(){this.ha=void 0;this.M=this.O=this.p=null;this.N=0;this.ub=null;this.t="";this.v=this.L=this.Aa=void 0;this.name="";this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function w(a,b,c,d){var f=new v;f.p={};f.ub=a;f.t=b;f.v=h=>h===f;f.name=c;f.isPrimitive=!0;f.isInstance=()=>!1;void 0!==d&&(f.L=Ia(f,d));return f}
function x(a,b,c,d){var f=new v,h=ca(a);f.p=c;f.t="L"+b+";";f.v=g=>!!g.p[h];f.name=b;f.isInterface=!1;f.isInstance=d||(g=>!!(g&&g.$classData&&g.$classData.p[h]));return f}function Ia(a,b,c){var d=new v;b.prototype.$classData=d;var f="["+a.t;d.ha=b;d.p={a:1,ja:1,b:1};d.O=a;d.M=a;d.N=1;d.t=f;d.name=f;d.isArrayClass=!0;d.v=c||(h=>d===h);d.isInstance=h=>h instanceof b;return d}
function Ja(a){function b(m){if("number"===typeof m){this.c=Array(m);for(var p=0;p<m;p++)this.c[p]=null}else this.c=m}var c=new v;b.prototype=new za;b.prototype.constructor=b;var d=a.M||a,f=a.N+1;b.prototype.$classData=c;var h="["+a.t;c.ha=b;c.p={a:1,ja:1,b:1};c.O=a;c.M=d;c.N=f;c.t=h;c.name=h;c.isArrayClass=!0;var g=m=>{var p=m.N;return p===f?d.v(m.M):p>f&&d===y};c.v=g;c.isInstance=m=>{m=m&&m.$classData;return!!m&&(m===c||g(m))};return c}function Ka(a){a.L||(a.L=Ja(a));return a.L}
function l(a){a.Aa||(a.Aa=new z(a));return a.Aa}v.prototype.isAssignableFrom=function(a){return this===a||this.v(a)};v.prototype.checkCast=function(){};v.prototype.getSuperclass=function(){return this.Zb?l(this.Zb):null};v.prototype.getComponentType=function(){return this.O?l(this.O):null};v.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b=Ka(b);return ea(b,a,0)};var y=new v;y.p={a:1};y.t="Ljava.lang.Object;";y.v=a=>!a.isPrimitive;y.name="java.lang.Object";
y.isInstance=a=>null!==a;y.L=Ia(y,u,a=>{var b=a.N;return 1===b?!a.M.isPrimitive:1<b});r.prototype.$classData=y;w(void 0,"V","void",void 0);w(!1,"Z","boolean",Aa);w(0,"C","char",Ba);w(0,"B","byte",Ca);w(0,"S","short",Da);w(0,"I","int",Ea);var La=w(null,"J","long",Fa);w(0,"F","float",Ga);w(0,"D","double",Ha);function Ma(){Na||(Na=new Oa);var a=Na;0===(33554432&a.da)&&0===(33554432&a.da)&&(a.Qa=window,a.da|=33554432);a.Qa.document.documentElement}Ma.prototype=new t;Ma.prototype.constructor=Ma;
Ma.prototype.$classData=x({vb:0},"dotty.tools.scaladoc.ContentContributors",{vb:1,a:1});function z(a){this.D=a}z.prototype=new t;z.prototype.constructor=z;z.prototype.i=function(){return(this.D.isInterface?"interface ":this.D.isPrimitive?"":"class ")+this.D.name};z.prototype.$classData=x({Gb:0},"java.lang.Class",{Gb:1,a:1});
function Pa(){this.Wa=this.ka=this.P=null;Qa=this;this.P=new ArrayBuffer(8);this.ka=new Int32Array(this.P,0,2);new Float32Array(this.P,0,2);this.Wa=new Float64Array(this.P,0,1);this.ka[0]=16909060;new Int8Array(this.P,0,8)}Pa.prototype=new t;Pa.prototype.constructor=Pa;function Ra(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;a.Wa[0]=b;return(a.ka[0]|0)^(a.ka[1]|0)}Pa.prototype.$classData=x({Jb:0},"java.lang.FloatingPointBits$",{Jb:1,a:1});var Qa;function Sa(){Qa||(Qa=new Pa);return Qa}
function Ta(){this.Xa=this.Ca=null;Ua=this;var a={"java.version":"1.8","java.vm.specification.version":"1.8","java.vm.specification.vendor":"Oracle Corporation","java.vm.specification.name":"Java Virtual Machine Specification","java.vm.name":"Scala.js"};a["java.vm.version"]=aa.linkerVersion;a["java.specification.version"]="1.8";a["java.specification.vendor"]="Oracle Corporation";a["java.specification.name"]="Java Platform API Specification";a["file.separator"]="/";a["path.separator"]=":";a["line.separator"]=
"\n";this.Ca=a;this.Xa=null}Ta.prototype=new t;Ta.prototype.constructor=Ta;function Va(a,b,c){return null!==a.Ca?(a=a.Ca,Wa||(Wa=new Xa),Wa.Za.call(a,b)?a[b]:c):Va(a.Xa,b,c)}Ta.prototype.$classData=x({Sb:0},"java.lang.System$SystemProperties$",{Sb:1,a:1});var Ua;function Xa(){this.Za=null;Wa=this;this.Za=Object.prototype.hasOwnProperty}Xa.prototype=new t;Xa.prototype.constructor=Xa;Xa.prototype.$classData=x({Ub:0},"java.lang.Utils$Cache$",{Ub:1,a:1});
var Wa,qa=x({Vb:0},"java.lang.Void",{Vb:1,a:1},a=>void 0===a);function Ya(){}Ya.prototype=new t;Ya.prototype.constructor=Ya;Ya.prototype.$classData=x({Wb:0},"java.util.Arrays$",{Wb:1,a:1});var Za;function Oa(){this.Qa=null;this.da=0}Oa.prototype=new t;Oa.prototype.constructor=Oa;Oa.prototype.$classData=x({xb:0},"org.scalajs.dom.package$",{xb:1,a:1});var Na;function n(a,b){this.K=a;this.J=b}n.prototype=new t;n.prototype.constructor=n;n.prototype.u=function(){return this.K^this.J};
n.prototype.i=function(){$a();var a=this.K,b=this.J;return b===a>>31?""+a:0>b?"-"+ab(-a|0,0!==a?~b:-b|0):ab(a,b)};n.prototype.$classData=x({yb:0},"org.scalajs.linker.runtime.RuntimeLong",{yb:1,a:1});
function ab(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+(Math.clz32(1E9)|0)|0)-(0!==b?Math.clz32(b)|0:32+(Math.clz32(a)|0)|0)|0,d=c,f=0===(32&d)?1E9<<d:0;d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d;var h=a,g=b;for(a=b=0;0<=c&&0!==(-2097152&g);){var m=h,p=g,B=f,T=d;if(p===T?(-2147483648^m)>=(-2147483648^B):(-2147483648^p)>=(-2147483648^T))m=g,p=d,g=h-f|0,m=(-2147483648^g)>(-2147483648^h)?-1+(m-p|0)|0:m-p|0,h=g,g=m,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;m=d>>>1|0;f=f>>>1|0|d<<31;d=m}c=
g;if(0===c?-1147483648<=(-2147483648^h):-2147483648<=(-2147483648^c))c=4294967296*g+ +(h>>>0),h=c/1E9,f=h/4294967296|0,d=b,b=h=d+(h|0)|0,a=(-2147483648^h)<(-2147483648^d)?1+(a+f|0)|0:a+f|0,h=c%1E9|0;c=""+h;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length)+c}return b}function bb(){this.ea=0}bb.prototype=new t;bb.prototype.constructor=bb;
function cb(a,b){if(-0x7fffffffffffffff>b)return a.ea=-2147483648,0;if(0x7fffffffffffffff<=b)return a.ea=2147483647,-1;var c=b|0,d=b/4294967296|0;a.ea=0>b&&0!==c?-1+d|0:d;return c}bb.prototype.$classData=x({zb:0},"org.scalajs.linker.runtime.RuntimeLong$",{zb:1,a:1});var db;function $a(){db||(db=new bb);return db}function eb(a,b,c,d,f){var h=b.o;0!==c.length&&(h.e=""+h.e+c);a=a.k();if(a.h())for(c=a.g(),h.e=""+h.e+c;a.h();)h.e=""+h.e+d,c=a.g(),h.e=""+h.e+c;0!==f.length&&(h.e=""+h.e+f);return b}
function fb(){gb=this}fb.prototype=new t;fb.prototype.constructor=fb;fb.prototype.$classData=x({nc:0},"scala.collection.StringOps$",{nc:1,a:1});var gb;function hb(){this.qb=null;ib=this;this.qb=new u(0)}hb.prototype=new t;hb.prototype.constructor=hb;hb.prototype.$classData=x({Ec:0},"scala.collection.immutable.VectorStatics$",{Ec:1,a:1});var ib;function lb(){ib||(ib=new hb);return ib}function mb(){}mb.prototype=new t;mb.prototype.constructor=mb;
mb.prototype.$classData=x({Nc:0},"scala.collection.mutable.MutationTracker$",{Nc:1,a:1});var nb;function ob(){this.ab=null;pb=this;qb||(qb=new A);qb||(qb=new A);rb||(rb=new sb);tb||(tb=new ub);C();vb();this.ab=D();wb();xb()}ob.prototype=new t;ob.prototype.constructor=ob;ob.prototype.$classData=x({ac:0},"scala.package$",{ac:1,a:1});var pb;function yb(){}yb.prototype=new t;yb.prototype.constructor=yb;
function E(a,b){if(null===b)return 0;if("number"===typeof b){a=+b;b=2147483647<a?2147483647:-2147483648>a?-2147483648:a|0;if(b===a)a=b;else{var c=$a();b=cb(c,a);c=c.ea;$a();a=(0>c?-(4294967296*+((0!==b?~c:-c|0)>>>0)+ +((-b|0)>>>0)):4294967296*c+ +(b>>>0))===a?b^c:Ra(Sa(),a)}return a}return b instanceof n?(a=null===b?ba:b,b=new n(a.K,a.J),a=b.K,b=b.J,b===a>>31?a:a^b):ua(b)}yb.prototype.$classData=x({Xc:0},"scala.runtime.Statics$",{Xc:1,a:1});var zb;function F(){zb||(zb=new yb);return zb}
function Ab(){}Ab.prototype=new t;Ab.prototype.constructor=Ab;function Bb(){}Bb.prototype=Ab.prototype;function G(a,b){a=Cb(a,b);return-430675100+Math.imul(5,a<<13|a>>>19|0)|0}function Cb(a,b){b=Math.imul(-862048943,b);b=Math.imul(461845907,b<<15|b>>>17|0);return a^b}function H(a){a=Math.imul(-2048144789,a^(a>>>16|0));a=Math.imul(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}
function Db(a){0===(32&a.ia)<<24>>24&&0===(32&a.ia)<<24>>24&&(a.Va=new Ea(new Int32Array([1632,1776,1984,2406,2534,2662,2790,2918,3046,3174,3302,3430,3664,3792,3872,4160,4240,6112,6160,6470,6608,6784,6800,6992,7088,7232,7248,42528,43216,43264,43472,43600,44016,65296,66720,69734,69872,69942,70096,71360,120782,120792,120802,120812,120822])),a.ia=(32|a.ia)<<24>>24);return a.Va}function Eb(){this.Va=null;this.ia=0}Eb.prototype=new t;Eb.prototype.constructor=Eb;
Eb.prototype.$classData=x({Fb:0},"java.lang.Character$",{Fb:1,a:1,b:1});var Fb;function Gb(a){throw new Hb('For input string: "'+a+'"');}function Ib(){}Ib.prototype=new t;Ib.prototype.constructor=Ib;Ib.prototype.$classData=x({Mb:0},"java.lang.Integer$",{Mb:1,a:1,b:1});var Jb;function I(a,b){a.Ya=b;"[object Error]"!==Object.prototype.toString.call(a)&&(void 0===Error.captureStackTrace?Error():Error.captureStackTrace(a))}
class Kb extends Error{constructor(){super();this.Ya=null}Ba(){return this.Ya}i(){var a=ta(this),b=this.Ba();return null===b?a:a+": "+b}u(){return r.prototype.u.call(this)}get message(){var a=this.Ba();return null===a?"":a}get name(){return ta(this)}toString(){return this.i()}}function Lb(){}Lb.prototype=new t;Lb.prototype.constructor=Lb;function Mb(){}Mb.prototype=Lb.prototype;Lb.prototype.i=function(){return"\x3cfunction0\x3e"};function J(a){this.Na=a}J.prototype=new t;J.prototype.constructor=J;
J.prototype.i=function(){return""+this.Na};J.prototype.$classData=x({Vc:0},"scala.runtime.IntRef",{Vc:1,a:1,b:1});function K(a){this.Oa=a}K.prototype=new t;K.prototype.constructor=K;K.prototype.i=function(){return""+this.Oa};K.prototype.$classData=x({Wc:0},"scala.runtime.ObjectRef",{Wc:1,a:1,b:1});
function Nb(){this.bb=this.pa=0;Ob=this;this.pa=q("Seq");this.bb=q("Map");q("Set");pb||(pb=new ob);for(var a=this.bb,b=0,c=0,d=0,f=1,h=pb.ab.k();h.h();){var g=h.g();g=E(F(),g);b=b+g|0;c^=g;f=Math.imul(f,1|g);d=1+d|0}a=G(a,b);a=G(a,c);a=Cb(a,f);H(a^d)}Nb.prototype=new Bb;Nb.prototype.constructor=Nb;Nb.prototype.$classData=x({bc:0},"scala.util.hashing.MurmurHash3$",{bc:1,dd:1,a:1});var Ob;function Pb(){this.Pa=null;Qb=this;var a=$a(),b=+(new Date).getTime();cb(a,b);this.Pa=new Rb;new Ma}
Pb.prototype=new t;Pb.prototype.constructor=Pb;Pb.prototype.$classData=x({wb:0},"dotty.tools.scaladoc.Main$",{wb:1,a:1,bd:1,ad:1});var Qb;class Sb extends Kb{}function Tb(){}Tb.prototype=new t;Tb.prototype.constructor=Tb;function Ub(){}Ub.prototype=Tb.prototype;function Vb(a,b){if(0>b)return 1;var c=a.E();if(0<=c)return c===b?0:c<b?-1:1;c=0;for(a=a.k();a.h();){if(c===b)return 1;a.g();c=1+c|0}return c-b|0}function Wb(){this.z=null;Xb=this;this.z=new L}Wb.prototype=new t;Wb.prototype.constructor=Wb;
Wb.prototype.$classData=x({hc:0},"scala.collection.Iterator$",{hc:1,a:1,y:1,b:1});var Xb;function C(){Xb||(Xb=new Wb);return Xb}function M(){}M.prototype=new t;M.prototype.constructor=M;M.prototype.C=function(){throw new Yb("head of empty lazy list");};function N(){throw new Zb("tail of empty lazy list");}M.prototype.$classData=x({tc:0},"scala.collection.immutable.LazyList$State$Empty$",{tc:1,a:1,od:1,b:1});var $b;function ac(){$b||($b=new M);return $b}function O(a){this.ya=a}O.prototype=new Mb;
O.prototype.constructor=O;O.prototype.$classData=x({Uc:0},"scala.scalajs.runtime.AnonFunction0",{Uc:1,xd:1,a:1,Yc:1});var pa=x({Cb:0},"java.lang.Boolean",{Cb:1,a:1,b:1,q:1,s:1},a=>"boolean"===typeof a),sa=x({Eb:0},"java.lang.Character",{Eb:1,a:1,b:1,q:1,s:1},a=>a instanceof k);class P extends Sb{}P.prototype.$classData=x({r:0},"java.lang.RuntimeException",{r:1,w:1,x:1,a:1,b:1});function bc(a){a.e="";return a}function Q(){this.e=null}Q.prototype=new t;Q.prototype.constructor=Q;Q.prototype.i=function(){return this.e};
Q.prototype.f=function(){return this.e.length};Q.prototype.$classData=x({Rb:0},"java.lang.StringBuilder",{Rb:1,a:1,Ua:1,Zc:1,b:1});function R(){}R.prototype=new t;R.prototype.constructor=R;function cc(){}cc.prototype=R.prototype;R.prototype.k=function(){return this};R.prototype.d=function(){return!this.h()};R.prototype.i=function(){return"\x3citerator\x3e"};R.prototype.fa=function(a,b,c,d){return eb(this,a,b,c,d)};function A(){dc||(dc=new ec)}A.prototype=new Ub;A.prototype.constructor=A;
A.prototype.$classData=x({fc:0},"scala.collection.Iterable$",{fc:1,gc:1,a:1,y:1,b:1});var qb;function fc(){}fc.prototype=new t;fc.prototype.constructor=fc;function gc(){}gc.prototype=fc.prototype;function ec(){vb()}ec.prototype=new Ub;ec.prototype.constructor=ec;ec.prototype.$classData=x({pc:0},"scala.collection.immutable.Iterable$",{pc:1,gc:1,a:1,y:1,b:1});var dc;function hc(){this.jb=null;ic=this;this.jb=jc(new S(new O(()=>ac())))}hc.prototype=new t;hc.prototype.constructor=hc;
function kc(a,b,c){var d=new K(b),f=new J(c);return new S(new O(()=>{for(var h=d.Oa,g=f.Na;0<g&&!h.d();)h=N(U(h)),d.Oa=h,g=-1+g|0,f.Na=g;return U(h)}))}hc.prototype.$classData=x({rc:0},"scala.collection.immutable.LazyList$",{rc:1,a:1,ta:1,y:1,b:1});var ic;function wb(){ic||(ic=new hc);return ic}var ja=x({Db:0},"java.lang.Byte",{Db:1,Q:1,a:1,b:1,q:1,s:1},a=>"number"===typeof a&&a<<24>>24===a&&1/a!==1/-0);class lc extends P{}class mc extends P{constructor(a){super();I(this,a)}}
mc.prototype.$classData=x({Kb:0},"java.lang.IndexOutOfBoundsException",{Kb:1,r:1,w:1,x:1,a:1,b:1});x({Ob:0},"java.lang.NullPointerException",{Ob:1,r:1,w:1,x:1,a:1,b:1});var ka=x({Qb:0},"java.lang.Short",{Qb:1,Q:1,a:1,b:1,q:1,s:1},a=>"number"===typeof a&&a<<16>>16===a&&1/a!==1/-0);class Zb extends P{constructor(a){super();I(this,a)}}Zb.prototype.$classData=x({Tb:0},"java.lang.UnsupportedOperationException",{Tb:1,r:1,w:1,x:1,a:1,b:1});
class nc extends P{constructor(){super();I(this,"mutation occurred during iteration")}}nc.prototype.$classData=x({Xb:0},"java.util.ConcurrentModificationException",{Xb:1,r:1,w:1,x:1,a:1,b:1});class Yb extends P{constructor(a){super();I(this,a)}}Yb.prototype.$classData=x({Yb:0},"java.util.NoSuchElementException",{Yb:1,r:1,w:1,x:1,a:1,b:1});
class oc extends P{constructor(a){super();this.$a=null;this.Da=!1;this.na=a;I(this,null)}Ba(){if(!this.Da&&!this.Da){if(null===this.na)var a="null";else try{var b=this.na;a=(void 0===b?"undefined":b.toString())+" (of class "+fa(this.na).D.name+")"}catch(c){a="an instance of class "+fa(this.na).D.name}this.$a=a;this.Da=!0}return this.$a}}oc.prototype.$classData=x({$b:0},"scala.MatchError",{$b:1,r:1,w:1,x:1,a:1,b:1});function L(){}L.prototype=new cc;L.prototype.constructor=L;L.prototype.h=function(){return!1};
L.prototype.g=function(){throw new Yb("next on empty iterator");};L.prototype.$classData=x({ic:0},"scala.collection.Iterator$$anon$19",{ic:1,Ea:1,a:1,ra:1,l:1,m:1});function pc(a,b){if(0>b)throw new mc(""+b);a=a.Sa(b);if(a.d())throw new mc(""+b);return a.Ta()}function ub(){xb()}ub.prototype=new gc;ub.prototype.constructor=ub;ub.prototype.$classData=x({oc:0},"scala.collection.immutable.IndexedSeq$",{oc:1,lc:1,a:1,ta:1,y:1,b:1});var tb;function V(a){this.Ha=a}V.prototype=new cc;
V.prototype.constructor=V;V.prototype.h=function(){return!this.Ha.d()};V.prototype.g=function(){if(this.Ha.d())return C().z.g();U(this.Ha).C()};V.prototype.$classData=x({sc:0},"scala.collection.immutable.LazyList$LazyIterator",{sc:1,Ea:1,a:1,ra:1,l:1,m:1});function qc(){rc=this;D();D()}qc.prototype=new t;qc.prototype.constructor=qc;qc.prototype.$classData=x({wc:0},"scala.collection.immutable.List$",{wc:1,a:1,mc:1,ta:1,y:1,b:1});var rc;function vb(){rc||(rc=new qc)}
function sc(a,b,c){this.mb=this.va=this.$=this.Z=this.Y=null;this.wa=b;this.yc=c;this.G=a.I;this.Ka=this.G.c.length;this.La=this.n=0;this.A=this.wa;this.ba=0;this.H=1;this.Ma=0;this.aa=this.Ka}sc.prototype=new t;sc.prototype.constructor=sc;e=sc.prototype;e.k=function(){return this};e.d=function(){return this.A<=this.n};e.i=function(){return"\x3citerator\x3e"};e.fa=function(a,b,c,d){return eb(this,a,b,c,d)};e.h=function(){return this.A>this.n};
e.g=function(){if(this.n===this.Ka){var a=(this.n-this.A|0)+this.wa|0;if(a===this.aa){this.A<=this.n&&C().z.g();this.ba=1+this.ba|0;for(var b=null;0===b.c.length;)this.ba=1+this.ba|0,b=null;this.Ma=this.aa;var c=this.yc/2|0,d=this.ba-c|0;c=this.H=(1+c|0)-(0>d?-d|0:d)|0;switch(c){case 1:this.G=b;break;case 2:this.Y=b;break;case 3:this.Z=b;break;case 4:this.$=b;break;case 5:this.va=b;break;case 6:this.mb=b;break;default:throw new oc(c);}this.aa=this.Ma+Math.imul(b.c.length,1<<Math.imul(5,-1+this.H|
0))|0;this.aa>this.wa&&(this.aa=this.wa);1<this.H&&(this.La=-1+(1<<Math.imul(5,this.H))|0)}1<this.H&&(a=a-this.Ma|0,b=this.La^a,1024>b?this.G=this.Y.c[31&(a>>>5|0)]:(32768>b?this.Y=this.Z.c[31&(a>>>10|0)]:(1048576>b?this.Z=this.$.c[31&(a>>>15|0)]:(33554432>b?this.$=this.va.c[31&(a>>>20|0)]:(this.va=this.mb.c[a>>>25|0],this.$=this.va.c[0]),this.Z=this.$.c[0]),this.Y=this.Z.c[0]),this.G=this.Y.c[0]),this.La=a);this.A=this.A-this.n|0;a=this.G.c.length;b=this.A;this.Ka=a<b?a:b;this.n=0}a=this.G.c[this.n];
this.n=1+this.n|0;return a};e.$classData=x({xc:0},"scala.collection.immutable.NewVectorIterator",{xc:1,a:1,ra:1,l:1,m:1,ja:1});function sb(){vb()}sb.prototype=new gc;sb.prototype.constructor=sb;sb.prototype.$classData=x({Ac:0},"scala.collection.immutable.Seq$",{Ac:1,lc:1,a:1,ta:1,y:1,b:1});var rb;
function tc(){this.pb=null;yc=this;try{gb||(gb=new fb);var a=Va;Ua||(Ua=new Ta);var b=a(Ua,"scala.collection.immutable.Vector.defaultApplyPreferredMaxLength","250");Jb||(Jb=new Ib);var c=null===b?0:b.length;0===c&&Gb(b);var d=b.charCodeAt(0),f=45===d;a=f?2147483648:2147483647;d=f||43===d?1:0;d>=b.length&&Gb(b);for(f=0;d!==c;){Fb||(Fb=new Eb);var h=Fb,g=b.charCodeAt(d);if(256>g)var m=48<=g&&57>=g?-48+g|0:65<=g&&90>=g?-55+g|0:97<=g&&122>=g?-87+g|0:-1;else if(65313<=g&&65338>=g)m=-65303+g|0;else if(65345<=
g&&65370>=g)m=-65335+g|0;else{Za||(Za=new Ya);b:for(var p=Db(h),B=0,T=p.c.length;;){if(B===T){var jb=-1-B|0;break b}var kb=(B+T|0)>>>1|0,uc=p.c[kb],vc=g===uc?0:g<uc?-1:1;if(0>vc)T=kb;else{if(0===vc){jb=kb;break b}B=1+kb|0}}B=0>jb?-2-jb|0:jb;if(0>B)m=-1;else{var wc=g-Db(h).c[B]|0;m=9<wc?-1:wc}}var xc=10>m?m:-1;f=10*f+xc;(-1===xc||f>a)&&Gb(b);d=1+d|0}}catch(ed){throw ed;}this.pb=new sc(zc(),0,0)}tc.prototype=new t;tc.prototype.constructor=tc;
tc.prototype.$classData=x({Cc:0},"scala.collection.immutable.Vector$",{Cc:1,a:1,mc:1,ta:1,y:1,b:1});var yc;function xb(){yc||(yc=new tc);return yc}function W(a,b){this.sb=0;this.tb=a;this.Pc=b;this.sb=(0,b.ya)()|0}W.prototype=new cc;W.prototype.constructor=W;W.prototype.h=function(){nb||(nb=new mb);var a=this.sb;if(((0,this.Pc.ya)()|0)!==a)throw new nc;return this.tb.h()};W.prototype.g=function(){return this.tb.g()};
W.prototype.$classData=x({Oc:0},"scala.collection.mutable.MutationTracker$CheckedIterator",{Oc:1,Ea:1,a:1,ra:1,l:1,m:1});function va(a){return Ra(Sa(),a)}var oa=x({Hb:0},"java.lang.Double",{Hb:1,Q:1,a:1,b:1,q:1,s:1,la:1},a=>"number"===typeof a),na=x({Ib:0},"java.lang.Float",{Ib:1,Q:1,a:1,b:1,q:1,s:1,la:1},a=>ma(a)),la=x({Lb:0},"java.lang.Integer",{Lb:1,Q:1,a:1,b:1,q:1,s:1,la:1},a=>ia(a)),ra=x({Nb:0},"java.lang.Long",{Nb:1,Q:1,a:1,b:1,q:1,s:1,la:1},a=>a instanceof n);
class Hb extends lc{constructor(a){super();I(this,a)}}Hb.prototype.$classData=x({Pb:0},"java.lang.NumberFormatException",{Pb:1,$c:1,r:1,w:1,x:1,a:1,b:1});function q(a){for(var b=0,c=1,d=-1+a.length|0;0<=d;)b=b+Math.imul(a.charCodeAt(d),c)|0,c=Math.imul(31,c),d=-1+d|0;return b}var ha=x({Ab:0},"java.lang.String",{Ab:1,a:1,b:1,q:1,Ua:1,s:1,la:1},a=>"string"===typeof a);function Ac(){}Ac.prototype=new t;Ac.prototype.constructor=Ac;function Bc(){}Bc.prototype=Ac.prototype;Ac.prototype.ga=function(){return this.B()};
Ac.prototype.fa=function(a,b,c,d){return eb(this,a,b,c,d)};function X(a){this.S=0;this.ec=a;this.Fa=0;this.S=a.f()}X.prototype=new cc;X.prototype.constructor=X;X.prototype.h=function(){return 0<this.S};X.prototype.g=function(){if(0<this.S){var a=this.ec.j(this.Fa);this.Fa=1+this.Fa|0;this.S=-1+this.S|0;return a}return C().z.g()};X.prototype.$classData=x({dc:0},"scala.collection.IndexedSeqView$IndexedSeqViewIterator",{dc:1,Ea:1,a:1,ra:1,l:1,m:1,b:1});function Cc(){}Cc.prototype=new Bc;
Cc.prototype.constructor=Cc;function Dc(){}Dc.prototype=Cc.prototype;Cc.prototype.i=function(){return this.B()+"(\x3cnot computed\x3e)"};function Y(){}Y.prototype=new Bc;Y.prototype.constructor=Y;function Ec(){}Ec.prototype=Y.prototype;
Y.prototype.u=function(){Ob||(Ob=new Nb);var a=Ob;if(this&&this.$classData&&this.$classData.p.cb)a:{var b=a.pa;a=this.f();switch(a){case 0:a=H(b^0);break a;case 1:a=b;b=this.j(0);a=H(G(a,E(F(),b))^1);break a;default:var c=this.j(0),d=E(F(),c);c=b=G(b,d);var f=this.j(1);f=E(F(),f);var h=f-d|0;for(d=2;d<a;){b=G(b,f);var g=this.j(d);g=E(F(),g);if(h!==(g-f|0)){b=G(b,g);for(d=1+d|0;d<a;)c=this.j(d),b=G(b,E(F(),c)),d=1+d|0;a=H(b^a);break a}f=g;d=1+d|0}a=H(G(G(c,h),f))}}else if(this instanceof Fc){for(a=
a.pa;!this.d();)this.C();a=H(a^0)}else a:if(b=a.pa,a=this.k(),a.h())if(c=a.g(),a.h()){d=a.g();h=E(F(),c);c=b=G(b,h);f=E(F(),d);h=f-h|0;for(d=2;a.h();){b=G(b,f);g=a.g();g=E(F(),g);if(h!==(g-f|0)){b=G(b,g);for(d=1+d|0;a.h();)c=a.g(),b=G(b,E(F(),c)),d=1+d|0;a=H(b^d);break a}f=g;d=1+d|0}a=H(G(G(c,h),f))}else a=H(G(b,E(F(),c))^1);else a=H(b^0);return a};Y.prototype.i=function(){var a=this.ga()+"(";if(this.d())a=""+a+")";else{var b=this.fa,c=new Gc;c.o=bc(new Q);a=b.call(this,c,a,", ",")").o.e}return a};
Y.prototype.F=function(a){return Vb(this,a)};Y.prototype.d=function(){return 0===this.F(0)};function Hc(){}Hc.prototype=new Dc;Hc.prototype.constructor=Hc;function Ic(){}Ic.prototype=Hc.prototype;function Z(){this.ua=null}Z.prototype=new Ic;Z.prototype.constructor=Z;function Jc(){}Jc.prototype=Z.prototype;Z.prototype.j=function(a){return this.ua.j(a)};Z.prototype.f=function(){return this.ua.f()};Z.prototype.d=function(){return this.ua.d()};function Kc(a){this.ua=a}Kc.prototype=new Jc;
Kc.prototype.constructor=Kc;e=Kc.prototype;e.k=function(){return new X(this)};e.B=function(){return"IndexedSeqView"};e.F=function(a){var b=this.f();return b===a?0:b<a?-1:1};e.E=function(){return this.f()};e.$classData=x({cc:0},"scala.collection.IndexedSeqView$Id",{cc:1,id:1,ed:1,fd:1,R:1,a:1,T:1,l:1,V:1,m:1,U:1,kd:1,b:1,hd:1,W:1,gd:1,db:1});function Lc(){}Lc.prototype=new Ec;Lc.prototype.constructor=Lc;function Mc(){}Mc.prototype=Lc.prototype;function Nc(){}Nc.prototype=new Ec;
Nc.prototype.constructor=Nc;function Oc(){}Oc.prototype=Nc.prototype;function Pc(a,b,c,d){b.e=""+b.e+c;a.X?a.d()||U(a).C():b.e+="\x3cnot computed\x3e";b.e=""+b.e+d;return b}function S(a){this.lb=null;this.Ia=!1;this.kb=a;this.Ja=this.X=!1}S.prototype=new Mc;S.prototype.constructor=S;e=S.prototype;e.B=function(){return"LinearSeq"};e.f=function(){for(var a=this,b=0;!a.d();)b=1+b|0,a=a.za();return b};
e.F=function(a){if(0>a)a=1;else a:for(var b=this,c=0;;){if(c===a){a=b.d()?0:1;break a}if(b.d()){a=-1;break a}c=1+c|0;b=b.za()}return a};e.j=function(a){return pc(this,a)};function U(a){if(!a.Ia&&!a.Ia){if(a.Ja)throw a=new P,I(a,"self-referential LazyList or a derivation thereof has no more elements"),a;a.Ja=!0;try{var b=(0,a.kb.ya)()}finally{a.Ja=!1}a.X=!0;a.kb=null;a.lb=b;a.Ia=!0}return a.lb}e.d=function(){return U(this)===ac()};e.E=function(){return this.X&&this.d()?0:-1};e.Ta=function(){U(this).C()};
function jc(a){var b=a,c=a;for(b.d()||(b=N(U(b)));c!==b&&!b.d();){b=N(U(b));if(b.d())break;b=N(U(b));if(b===c)break;c=N(U(c))}return a}e.k=function(){return this.X&&this.d()?C().z:new V(this)};e.ga=function(){return"LazyList"};e.fa=function(a,b,c,d){jc(this);Pc(this,a.o,b,d);return a};e.i=function(){var a=new Q;bc(a);a.e="LazyList";return Pc(this,a,"(",")").e};e.Sa=function(a){return 0>=a?this:this.X&&this.d()?wb().jb:kc(wb(),this,a)};e.za=function(){return N(U(this))};
e.$classData=x({qc:0},"scala.collection.immutable.LazyList",{qc:1,hb:1,qa:1,R:1,a:1,T:1,l:1,V:1,m:1,U:1,sa:1,oa:1,ca:1,W:1,ma:1,nb:1,ib:1,ob:1,uc:1,jc:1,kc:1,vc:1,b:1});function Qc(){}Qc.prototype=new Oc;Qc.prototype.constructor=Qc;function Rc(){}Rc.prototype=Qc.prototype;function Sc(){this.I=null}Sc.prototype=new Mc;Sc.prototype.constructor=Sc;function Tc(){}e=Tc.prototype=Sc.prototype;e.B=function(){return"IndexedSeq"};e.F=function(a){var b=this.f();return b===a?0:b<a?-1:1};e.E=function(){return this.f()};
e.f=function(){return this instanceof Uc?this.Ga:this.I.c.length};e.k=function(){return zc()===this?xb().pb:new sc(this,this.f(),0)};e.ga=function(){return"Vector"};function Fc(){}Fc.prototype=new Mc;Fc.prototype.constructor=Fc;function Vc(){}e=Vc.prototype=Fc.prototype;e.B=function(){return"LinearSeq"};e.j=function(a){return pc(this,a)};e.d=function(){return this===D()};e.f=function(){for(var a=0;!this.d();)a=1+a|0,Wc();return a};
e.F=function(a){if(0>a)a=1;else a:for(;;){if(0===a){a=this.d()?0:1;break a}if(this.d()){a=-1;break a}Wc()}return a};e.ga=function(){return"List"};e.Sa=function(a){a:for(var b=this;;){if(0>=a||b.d())break a;a=-1+a|0;b=b.za()}return b};function Xc(){this.I=null}Xc.prototype=new Tc;Xc.prototype.constructor=Xc;function Yc(){}Yc.prototype=Xc.prototype;function Uc(){this.I=null;this.Ga=0}Uc.prototype=new Yc;Uc.prototype.constructor=Uc;function Zc(){}Zc.prototype=Uc.prototype;
function $c(){ad=this;D();D()}$c.prototype=new Vc;$c.prototype.constructor=$c;e=$c.prototype;e.C=function(){throw new Yb("head of empty list");};function Wc(){throw new Zb("tail of empty list");}e.E=function(){return 0};e.k=function(){return C().z};e.za=function(){Wc()};e.Ta=function(){this.C()};e.$classData=x({zc:0},"scala.collection.immutable.Nil$",{zc:1,pd:1,hb:1,qa:1,R:1,a:1,T:1,l:1,V:1,m:1,U:1,sa:1,oa:1,ca:1,W:1,ma:1,nb:1,ib:1,ob:1,uc:1,jc:1,kc:1,vc:1,jd:1,fb:1,eb:1,Bc:1,gb:1,b:1,cd:1});var ad;
function D(){ad||(ad=new $c);return ad}function bd(){this.I=null;this.Ga=0;var a=lb().qb;lb();this.Ga=0;this.I=a}bd.prototype=new Zc;bd.prototype.constructor=bd;bd.prototype.j=function(a){throw new mc(a+" is out of bounds (empty vector)");};bd.prototype.$classData=x({Dc:0},"scala.collection.immutable.Vector0$",{Dc:1,ld:1,rd:1,qd:1,hb:1,qa:1,R:1,a:1,T:1,l:1,V:1,m:1,U:1,sa:1,oa:1,ca:1,W:1,ma:1,nb:1,ib:1,ob:1,md:1,cb:1,db:1,nd:1,Bc:1,fb:1,eb:1,gb:1,b:1});var cd;
function zc(){cd||(cd=new bd);return cd}function Gc(){this.o=null}Gc.prototype=new Oc;Gc.prototype.constructor=Gc;e=Gc.prototype;e.B=function(){return"IndexedSeq"};e.k=function(){var a=new Kc(this);return new X(a)};e.F=function(a){var b=this.o.f();return b===a?0:b<a?-1:1};e.f=function(){return this.o.f()};e.E=function(){return this.o.f()};e.i=function(){return this.o.e};e.d=function(){return 0===this.o.f()};e.j=function(a){return new k(this.o.e.charCodeAt(a))};
e.$classData=x({Tc:0},"scala.collection.mutable.StringBuilder",{Tc:1,Fc:1,qa:1,R:1,a:1,T:1,l:1,V:1,m:1,U:1,sa:1,oa:1,ca:1,W:1,ma:1,Rc:1,Kc:1,Sc:1,Ic:1,ja:1,Qc:1,Gc:1,Jc:1,Hc:1,ud:1,cb:1,db:1,vd:1,Ua:1,b:1});function Rb(){this.rb=null;this.Mc=this.xa=0;this.rb=D();this.xa=0}Rb.prototype=new Rc;Rb.prototype.constructor=Rb;e=Rb.prototype;e.k=function(){return new W(C().z,new O(()=>this.Mc))};e.j=function(a){return pc(this.rb,a)};e.f=function(){return this.xa};e.E=function(){return this.xa};
e.d=function(){return 0===this.xa};e.B=function(){return"ListBuffer"};e.$classData=x({Lc:0},"scala.collection.mutable.ListBuffer",{Lc:1,sd:1,Fc:1,qa:1,R:1,a:1,T:1,l:1,V:1,m:1,U:1,sa:1,oa:1,ca:1,W:1,ma:1,Rc:1,Kc:1,Sc:1,Ic:1,ja:1,td:1,Jc:1,Hc:1,wd:1,fb:1,eb:1,Qc:1,Gc:1,gb:1,b:1});ba=new n(0,0);La.ub=ba;new (Ka(ha).ha)([]);Qb||(Qb=new Pb);for(var dd=Qb.Pa.k();dd.h();)(0,dd.g().ya)();
}).call(this);
//# sourceMappingURL=scaladoc-js-contributors-opt.js.map
